// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/qesterrx/SafeKeeper/cmd/server/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// DataStorage is an autogenerated mock type for the DataStorage type
type DataStorage struct {
	mock.Mock
}

// GetObjectData provides a mock function with given fields: ctx, id, user
func (_m *DataStorage) GetObjectData(ctx context.Context, id int32, user int32) ([]byte, error) {
	ret := _m.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectData")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) ([]byte, error)); ok {
		return rf(ctx, id, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) []byte); ok {
		r0 = rf(ctx, id, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, id, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetObjectDesc provides a mock function with given fields: ctx, id, user
func (_m *DataStorage) GetObjectDesc(ctx context.Context, id int32, user int32) (*model.DBObject, error) {
	ret := _m.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectDesc")
	}

	var r0 *model.DBObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) (*model.DBObject, error)); ok {
		return rf(ctx, id, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) *model.DBObject); ok {
		r0 = rf(ctx, id, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DBObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, id, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetObjectListDesc provides a mock function with given fields: ctx, user
func (_m *DataStorage) GetObjectListDesc(ctx context.Context, user int32) ([]*model.DBObject, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectListDesc")
	}

	var r0 []*model.DBObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]*model.DBObject, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []*model.DBObject); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.DBObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewObject provides a mock function with given fields: ctx, object
func (_m *DataStorage) NewObject(ctx context.Context, object *model.DBObject) (int32, error) {
	ret := _m.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for NewObject")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.DBObject) (int32, error)); ok {
		return rf(ctx, object)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.DBObject) int32); ok {
		r0 = rf(ctx, object)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.DBObject) error); ok {
		r1 = rf(ctx, object)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateObject provides a mock function with given fields: ctx, object
func (_m *DataStorage) UpdateObject(ctx context.Context, object *model.DBObject) error {
	ret := _m.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for UpdateObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.DBObject) error); ok {
		r0 = rf(ctx, object)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDataStorage creates a new instance of DataStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataStorage {
	mock := &DataStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
