CREATE TABLE IF NOT EXISTS TUSERS (
DFUSER INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
DFLOGIN VARCHAR(255) NOT NULL UNIQUE,
DFPASSWORD VARCHAR(255) NOT NULL,
DFAESTOKEN VARCHAR(4048) NOT NULL,
DFCREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_USERS_LOGIN ON TUSERS(DFLOGIN);
