CREATE TABLE IF NOT EXISTS TOBJECTS (
DFOBJECT INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
DFUSER BIGINT NOT NULL,
DFNAME VARCHAR(255) NOT NULL,
DFKIND VARCHAR(255) NOT NULL,
DFDATA BYTEA,
DFCHECKSUM VARCHAR(4048) NOT NULL,
DFUPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DFVERSION BIGINT NOT NULL,
DFCLIENT BIGINT NOT NULL,
DFDELETED BOOL NOT NULL
);

CREATE INDEX IDX_OBJECTS_USER ON TOBJECTS(DFUSER);