// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: data/data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NewSafeDataRequest
type SafeDataMeta struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Kind        *string                `protobuf:"bytes,3,opt,name=kind"`
	xxx_hidden_Version     int32                  `protobuf:"varint,4,opt,name=version"`
	xxx_hidden_Checksum    *string                `protobuf:"bytes,5,opt,name=checksum"`
	xxx_hidden_Updated     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated"`
	xxx_hidden_Client      int32                  `protobuf:"varint,7,opt,name=client"`
	xxx_hidden_Deleted     bool                   `protobuf:"varint,8,opt,name=deleted"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SafeDataMeta) Reset() {
	*x = SafeDataMeta{}
	mi := &file_data_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeDataMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeDataMeta) ProtoMessage() {}

func (x *SafeDataMeta) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SafeDataMeta) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *SafeDataMeta) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *SafeDataMeta) GetKind() string {
	if x != nil {
		if x.xxx_hidden_Kind != nil {
			return *x.xxx_hidden_Kind
		}
		return ""
	}
	return ""
}

func (x *SafeDataMeta) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *SafeDataMeta) GetChecksum() string {
	if x != nil {
		if x.xxx_hidden_Checksum != nil {
			return *x.xxx_hidden_Checksum
		}
		return ""
	}
	return ""
}

func (x *SafeDataMeta) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Updated
	}
	return nil
}

func (x *SafeDataMeta) GetClient() int32 {
	if x != nil {
		return x.xxx_hidden_Client
	}
	return 0
}

func (x *SafeDataMeta) GetDeleted() bool {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return false
}

func (x *SafeDataMeta) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *SafeDataMeta) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *SafeDataMeta) SetKind(v string) {
	x.xxx_hidden_Kind = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *SafeDataMeta) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *SafeDataMeta) SetChecksum(v string) {
	x.xxx_hidden_Checksum = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *SafeDataMeta) SetUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Updated = v
}

func (x *SafeDataMeta) SetClient(v int32) {
	x.xxx_hidden_Client = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *SafeDataMeta) SetDeleted(v bool) {
	x.xxx_hidden_Deleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *SafeDataMeta) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SafeDataMeta) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SafeDataMeta) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SafeDataMeta) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SafeDataMeta) HasChecksum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *SafeDataMeta) HasUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Updated != nil
}

func (x *SafeDataMeta) HasClient() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *SafeDataMeta) HasDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *SafeDataMeta) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *SafeDataMeta) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *SafeDataMeta) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Kind = nil
}

func (x *SafeDataMeta) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Version = 0
}

func (x *SafeDataMeta) ClearChecksum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Checksum = nil
}

func (x *SafeDataMeta) ClearUpdated() {
	x.xxx_hidden_Updated = nil
}

func (x *SafeDataMeta) ClearClient() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Client = 0
}

func (x *SafeDataMeta) ClearDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Deleted = false
}

type SafeDataMeta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       *int32
	Name     *string
	Kind     *string
	Version  *int32
	Checksum *string
	Updated  *timestamppb.Timestamp
	Client   *int32
	Deleted  *bool
}

func (b0 SafeDataMeta_builder) Build() *SafeDataMeta {
	m0 := &SafeDataMeta{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Name = b.Name
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Kind = b.Kind
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Version = *b.Version
	}
	if b.Checksum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Checksum = b.Checksum
	}
	x.xxx_hidden_Updated = b.Updated
	if b.Client != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_Client = *b.Client
	}
	if b.Deleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_Deleted = *b.Deleted
	}
	return m0
}

type SafeDataChunk struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_Offset      int32                  `protobuf:"varint,2,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SafeDataChunk) Reset() {
	*x = SafeDataChunk{}
	mi := &file_data_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeDataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeDataChunk) ProtoMessage() {}

func (x *SafeDataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SafeDataChunk) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *SafeDataChunk) GetOffset() int32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *SafeDataChunk) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SafeDataChunk) SetOffset(v int32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SafeDataChunk) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SafeDataChunk) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SafeDataChunk) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

func (x *SafeDataChunk) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Offset = 0
}

type SafeDataChunk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data   []byte
	Offset *int32
}

func (b0 SafeDataChunk_builder) Build() *SafeDataChunk {
	m0 := &SafeDataChunk{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Data = b.Data
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

type NewSafeDataRequest struct {
	state                  protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_RequestType isNewSafeDataRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NewSafeDataRequest) Reset() {
	*x = NewSafeDataRequest{}
	mi := &file_data_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSafeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSafeDataRequest) ProtoMessage() {}

func (x *NewSafeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NewSafeDataRequest) GetMeta() *SafeDataMeta {
	if x != nil {
		if x, ok := x.xxx_hidden_RequestType.(*newSafeDataRequest_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *NewSafeDataRequest) GetChunk() *SafeDataChunk {
	if x != nil {
		if x, ok := x.xxx_hidden_RequestType.(*newSafeDataRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *NewSafeDataRequest) SetMeta(v *SafeDataMeta) {
	if v == nil {
		x.xxx_hidden_RequestType = nil
		return
	}
	x.xxx_hidden_RequestType = &newSafeDataRequest_Meta{v}
}

func (x *NewSafeDataRequest) SetChunk(v *SafeDataChunk) {
	if v == nil {
		x.xxx_hidden_RequestType = nil
		return
	}
	x.xxx_hidden_RequestType = &newSafeDataRequest_Chunk{v}
}

func (x *NewSafeDataRequest) HasRequestType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RequestType != nil
}

func (x *NewSafeDataRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_RequestType.(*newSafeDataRequest_Meta)
	return ok
}

func (x *NewSafeDataRequest) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_RequestType.(*newSafeDataRequest_Chunk)
	return ok
}

func (x *NewSafeDataRequest) ClearRequestType() {
	x.xxx_hidden_RequestType = nil
}

func (x *NewSafeDataRequest) ClearMeta() {
	if _, ok := x.xxx_hidden_RequestType.(*newSafeDataRequest_Meta); ok {
		x.xxx_hidden_RequestType = nil
	}
}

func (x *NewSafeDataRequest) ClearChunk() {
	if _, ok := x.xxx_hidden_RequestType.(*newSafeDataRequest_Chunk); ok {
		x.xxx_hidden_RequestType = nil
	}
}

const NewSafeDataRequest_RequestType_not_set_case case_NewSafeDataRequest_RequestType = 0
const NewSafeDataRequest_Meta_case case_NewSafeDataRequest_RequestType = 1
const NewSafeDataRequest_Chunk_case case_NewSafeDataRequest_RequestType = 2

func (x *NewSafeDataRequest) WhichRequestType() case_NewSafeDataRequest_RequestType {
	if x == nil {
		return NewSafeDataRequest_RequestType_not_set_case
	}
	switch x.xxx_hidden_RequestType.(type) {
	case *newSafeDataRequest_Meta:
		return NewSafeDataRequest_Meta_case
	case *newSafeDataRequest_Chunk:
		return NewSafeDataRequest_Chunk_case
	default:
		return NewSafeDataRequest_RequestType_not_set_case
	}
}

type NewSafeDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_RequestType:
	Meta  *SafeDataMeta
	Chunk *SafeDataChunk
	// -- end of xxx_hidden_RequestType
}

func (b0 NewSafeDataRequest_builder) Build() *NewSafeDataRequest {
	m0 := &NewSafeDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Meta != nil {
		x.xxx_hidden_RequestType = &newSafeDataRequest_Meta{b.Meta}
	}
	if b.Chunk != nil {
		x.xxx_hidden_RequestType = &newSafeDataRequest_Chunk{b.Chunk}
	}
	return m0
}

type case_NewSafeDataRequest_RequestType protoreflect.FieldNumber

func (x case_NewSafeDataRequest_RequestType) String() string {
	md := file_data_data_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isNewSafeDataRequest_RequestType interface {
	isNewSafeDataRequest_RequestType()
}

type newSafeDataRequest_Meta struct {
	Meta *SafeDataMeta `protobuf:"bytes,1,opt,name=meta,oneof"`
}

type newSafeDataRequest_Chunk struct {
	Chunk *SafeDataChunk `protobuf:"bytes,2,opt,name=chunk,oneof"`
}

func (*newSafeDataRequest_Meta) isNewSafeDataRequest_RequestType() {}

func (*newSafeDataRequest_Chunk) isNewSafeDataRequest_RequestType() {}

// NewSafeDataResponse
type NewSafeDataResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Version     int32                  `protobuf:"varint,2,opt,name=version"`
	xxx_hidden_Updated     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NewSafeDataResponse) Reset() {
	*x = NewSafeDataResponse{}
	mi := &file_data_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSafeDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSafeDataResponse) ProtoMessage() {}

func (x *NewSafeDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NewSafeDataResponse) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *NewSafeDataResponse) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *NewSafeDataResponse) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Updated
	}
	return nil
}

func (x *NewSafeDataResponse) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *NewSafeDataResponse) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *NewSafeDataResponse) SetUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Updated = v
}

func (x *NewSafeDataResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *NewSafeDataResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *NewSafeDataResponse) HasUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Updated != nil
}

func (x *NewSafeDataResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *NewSafeDataResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = 0
}

func (x *NewSafeDataResponse) ClearUpdated() {
	x.xxx_hidden_Updated = nil
}

type NewSafeDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *int32
	Version *int32
	Updated *timestamppb.Timestamp
}

func (b0 NewSafeDataResponse_builder) Build() *NewSafeDataResponse {
	m0 := &NewSafeDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Version = *b.Version
	}
	x.xxx_hidden_Updated = b.Updated
	return m0
}

// DelSafeDataRequest
type DelSafeDataRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Version     int32                  `protobuf:"varint,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DelSafeDataRequest) Reset() {
	*x = DelSafeDataRequest{}
	mi := &file_data_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelSafeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSafeDataRequest) ProtoMessage() {}

func (x *DelSafeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DelSafeDataRequest) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DelSafeDataRequest) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *DelSafeDataRequest) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DelSafeDataRequest) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DelSafeDataRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DelSafeDataRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DelSafeDataRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *DelSafeDataRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = 0
}

type DelSafeDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *int32
	Version *int32
}

func (b0 DelSafeDataRequest_builder) Build() *DelSafeDataRequest {
	m0 := &DelSafeDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

// EditSafeDataRequest
type EditSafeDataRequest struct {
	state                  protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_RequestType isEditSafeDataRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EditSafeDataRequest) Reset() {
	*x = EditSafeDataRequest{}
	mi := &file_data_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditSafeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSafeDataRequest) ProtoMessage() {}

func (x *EditSafeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EditSafeDataRequest) GetMeta() *SafeDataMeta {
	if x != nil {
		if x, ok := x.xxx_hidden_RequestType.(*editSafeDataRequest_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *EditSafeDataRequest) GetChunk() *SafeDataChunk {
	if x != nil {
		if x, ok := x.xxx_hidden_RequestType.(*editSafeDataRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *EditSafeDataRequest) SetMeta(v *SafeDataMeta) {
	if v == nil {
		x.xxx_hidden_RequestType = nil
		return
	}
	x.xxx_hidden_RequestType = &editSafeDataRequest_Meta{v}
}

func (x *EditSafeDataRequest) SetChunk(v *SafeDataChunk) {
	if v == nil {
		x.xxx_hidden_RequestType = nil
		return
	}
	x.xxx_hidden_RequestType = &editSafeDataRequest_Chunk{v}
}

func (x *EditSafeDataRequest) HasRequestType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RequestType != nil
}

func (x *EditSafeDataRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_RequestType.(*editSafeDataRequest_Meta)
	return ok
}

func (x *EditSafeDataRequest) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_RequestType.(*editSafeDataRequest_Chunk)
	return ok
}

func (x *EditSafeDataRequest) ClearRequestType() {
	x.xxx_hidden_RequestType = nil
}

func (x *EditSafeDataRequest) ClearMeta() {
	if _, ok := x.xxx_hidden_RequestType.(*editSafeDataRequest_Meta); ok {
		x.xxx_hidden_RequestType = nil
	}
}

func (x *EditSafeDataRequest) ClearChunk() {
	if _, ok := x.xxx_hidden_RequestType.(*editSafeDataRequest_Chunk); ok {
		x.xxx_hidden_RequestType = nil
	}
}

const EditSafeDataRequest_RequestType_not_set_case case_EditSafeDataRequest_RequestType = 0
const EditSafeDataRequest_Meta_case case_EditSafeDataRequest_RequestType = 1
const EditSafeDataRequest_Chunk_case case_EditSafeDataRequest_RequestType = 2

func (x *EditSafeDataRequest) WhichRequestType() case_EditSafeDataRequest_RequestType {
	if x == nil {
		return EditSafeDataRequest_RequestType_not_set_case
	}
	switch x.xxx_hidden_RequestType.(type) {
	case *editSafeDataRequest_Meta:
		return EditSafeDataRequest_Meta_case
	case *editSafeDataRequest_Chunk:
		return EditSafeDataRequest_Chunk_case
	default:
		return EditSafeDataRequest_RequestType_not_set_case
	}
}

type EditSafeDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_RequestType:
	Meta  *SafeDataMeta
	Chunk *SafeDataChunk
	// -- end of xxx_hidden_RequestType
}

func (b0 EditSafeDataRequest_builder) Build() *EditSafeDataRequest {
	m0 := &EditSafeDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Meta != nil {
		x.xxx_hidden_RequestType = &editSafeDataRequest_Meta{b.Meta}
	}
	if b.Chunk != nil {
		x.xxx_hidden_RequestType = &editSafeDataRequest_Chunk{b.Chunk}
	}
	return m0
}

type case_EditSafeDataRequest_RequestType protoreflect.FieldNumber

func (x case_EditSafeDataRequest_RequestType) String() string {
	md := file_data_data_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isEditSafeDataRequest_RequestType interface {
	isEditSafeDataRequest_RequestType()
}

type editSafeDataRequest_Meta struct {
	Meta *SafeDataMeta `protobuf:"bytes,1,opt,name=meta,oneof"`
}

type editSafeDataRequest_Chunk struct {
	Chunk *SafeDataChunk `protobuf:"bytes,2,opt,name=chunk,oneof"`
}

func (*editSafeDataRequest_Meta) isEditSafeDataRequest_RequestType() {}

func (*editSafeDataRequest_Chunk) isEditSafeDataRequest_RequestType() {}

// EditSafeDataResponse
type EditSafeDataResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version     int32                  `protobuf:"varint,1,opt,name=version"`
	xxx_hidden_Updated     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EditSafeDataResponse) Reset() {
	*x = EditSafeDataResponse{}
	mi := &file_data_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditSafeDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSafeDataResponse) ProtoMessage() {}

func (x *EditSafeDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EditSafeDataResponse) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *EditSafeDataResponse) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Updated
	}
	return nil
}

func (x *EditSafeDataResponse) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *EditSafeDataResponse) SetUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Updated = v
}

func (x *EditSafeDataResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EditSafeDataResponse) HasUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Updated != nil
}

func (x *EditSafeDataResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Version = 0
}

func (x *EditSafeDataResponse) ClearUpdated() {
	x.xxx_hidden_Updated = nil
}

type EditSafeDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Version *int32
	Updated *timestamppb.Timestamp
}

func (b0 EditSafeDataResponse_builder) Build() *EditSafeDataResponse {
	m0 := &EditSafeDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Version = *b.Version
	}
	x.xxx_hidden_Updated = b.Updated
	return m0
}

type GetSafeDataRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSafeDataRequest) Reset() {
	*x = GetSafeDataRequest{}
	mi := &file_data_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSafeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSafeDataRequest) ProtoMessage() {}

func (x *GetSafeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSafeDataRequest) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *GetSafeDataRequest) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetSafeDataRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetSafeDataRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

type GetSafeDataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int32
}

func (b0 GetSafeDataRequest_builder) Build() *GetSafeDataRequest {
	m0 := &GetSafeDataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = *b.Id
	}
	return m0
}

type GetSafeDataResponse struct {
	state                  protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_RequestType isGetSafeDataResponse_RequestType `protobuf_oneof:"request_type"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSafeDataResponse) Reset() {
	*x = GetSafeDataResponse{}
	mi := &file_data_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSafeDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSafeDataResponse) ProtoMessage() {}

func (x *GetSafeDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSafeDataResponse) GetMeta() *SafeDataMeta {
	if x != nil {
		if x, ok := x.xxx_hidden_RequestType.(*getSafeDataResponse_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *GetSafeDataResponse) GetChunk() *SafeDataChunk {
	if x != nil {
		if x, ok := x.xxx_hidden_RequestType.(*getSafeDataResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *GetSafeDataResponse) SetMeta(v *SafeDataMeta) {
	if v == nil {
		x.xxx_hidden_RequestType = nil
		return
	}
	x.xxx_hidden_RequestType = &getSafeDataResponse_Meta{v}
}

func (x *GetSafeDataResponse) SetChunk(v *SafeDataChunk) {
	if v == nil {
		x.xxx_hidden_RequestType = nil
		return
	}
	x.xxx_hidden_RequestType = &getSafeDataResponse_Chunk{v}
}

func (x *GetSafeDataResponse) HasRequestType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RequestType != nil
}

func (x *GetSafeDataResponse) HasMeta() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_RequestType.(*getSafeDataResponse_Meta)
	return ok
}

func (x *GetSafeDataResponse) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_RequestType.(*getSafeDataResponse_Chunk)
	return ok
}

func (x *GetSafeDataResponse) ClearRequestType() {
	x.xxx_hidden_RequestType = nil
}

func (x *GetSafeDataResponse) ClearMeta() {
	if _, ok := x.xxx_hidden_RequestType.(*getSafeDataResponse_Meta); ok {
		x.xxx_hidden_RequestType = nil
	}
}

func (x *GetSafeDataResponse) ClearChunk() {
	if _, ok := x.xxx_hidden_RequestType.(*getSafeDataResponse_Chunk); ok {
		x.xxx_hidden_RequestType = nil
	}
}

const GetSafeDataResponse_RequestType_not_set_case case_GetSafeDataResponse_RequestType = 0
const GetSafeDataResponse_Meta_case case_GetSafeDataResponse_RequestType = 1
const GetSafeDataResponse_Chunk_case case_GetSafeDataResponse_RequestType = 2

func (x *GetSafeDataResponse) WhichRequestType() case_GetSafeDataResponse_RequestType {
	if x == nil {
		return GetSafeDataResponse_RequestType_not_set_case
	}
	switch x.xxx_hidden_RequestType.(type) {
	case *getSafeDataResponse_Meta:
		return GetSafeDataResponse_Meta_case
	case *getSafeDataResponse_Chunk:
		return GetSafeDataResponse_Chunk_case
	default:
		return GetSafeDataResponse_RequestType_not_set_case
	}
}

type GetSafeDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_RequestType:
	Meta  *SafeDataMeta
	Chunk *SafeDataChunk
	// -- end of xxx_hidden_RequestType
}

func (b0 GetSafeDataResponse_builder) Build() *GetSafeDataResponse {
	m0 := &GetSafeDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Meta != nil {
		x.xxx_hidden_RequestType = &getSafeDataResponse_Meta{b.Meta}
	}
	if b.Chunk != nil {
		x.xxx_hidden_RequestType = &getSafeDataResponse_Chunk{b.Chunk}
	}
	return m0
}

type case_GetSafeDataResponse_RequestType protoreflect.FieldNumber

func (x case_GetSafeDataResponse_RequestType) String() string {
	md := file_data_data_proto_msgTypes[8].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isGetSafeDataResponse_RequestType interface {
	isGetSafeDataResponse_RequestType()
}

type getSafeDataResponse_Meta struct {
	Meta *SafeDataMeta `protobuf:"bytes,1,opt,name=meta,oneof"`
}

type getSafeDataResponse_Chunk struct {
	Chunk *SafeDataChunk `protobuf:"bytes,2,opt,name=chunk,oneof"`
}

func (*getSafeDataResponse_Meta) isGetSafeDataResponse_RequestType() {}

func (*getSafeDataResponse_Chunk) isGetSafeDataResponse_RequestType() {}

type GetSafeDataListResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sobjects *[]*SafeDataMeta       `protobuf:"bytes,1,rep,name=sobjects"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetSafeDataListResponse) Reset() {
	*x = GetSafeDataListResponse{}
	mi := &file_data_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSafeDataListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSafeDataListResponse) ProtoMessage() {}

func (x *GetSafeDataListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSafeDataListResponse) GetSobjects() []*SafeDataMeta {
	if x != nil {
		if x.xxx_hidden_Sobjects != nil {
			return *x.xxx_hidden_Sobjects
		}
	}
	return nil
}

func (x *GetSafeDataListResponse) SetSobjects(v []*SafeDataMeta) {
	x.xxx_hidden_Sobjects = &v
}

type GetSafeDataListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sobjects []*SafeDataMeta
}

func (b0 GetSafeDataListResponse_builder) Build() *GetSafeDataListResponse {
	m0 := &GetSafeDataListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sobjects = &b.Sobjects
	return m0
}

var File_data_data_proto protoreflect.FileDescriptor

const file_data_data_proto_rawDesc = "" +
	"\n" +
	"\x0fdata/data.proto\x12\adata.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x01\n" +
	"\fSafeDataMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x124\n" +
	"\aupdated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\x12\x16\n" +
	"\x06client\x18\a \x01(\x05R\x06client\x12\x18\n" +
	"\adeleted\x18\b \x01(\bR\adeleted\";\n" +
	"\rSafeDataChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x81\x01\n" +
	"\x12NewSafeDataRequest\x12+\n" +
	"\x04meta\x18\x01 \x01(\v2\x15.data.v1.SafeDataMetaH\x00R\x04meta\x12.\n" +
	"\x05chunk\x18\x02 \x01(\v2\x16.data.v1.SafeDataChunkH\x00R\x05chunkB\x0e\n" +
	"\frequest_type\"u\n" +
	"\x13NewSafeDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x124\n" +
	"\aupdated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\">\n" +
	"\x12DelSafeDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\x82\x01\n" +
	"\x13EditSafeDataRequest\x12+\n" +
	"\x04meta\x18\x01 \x01(\v2\x15.data.v1.SafeDataMetaH\x00R\x04meta\x12.\n" +
	"\x05chunk\x18\x02 \x01(\v2\x16.data.v1.SafeDataChunkH\x00R\x05chunkB\x0e\n" +
	"\frequest_type\"f\n" +
	"\x14EditSafeDataResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x124\n" +
	"\aupdated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\"$\n" +
	"\x12GetSafeDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x82\x01\n" +
	"\x13GetSafeDataResponse\x12+\n" +
	"\x04meta\x18\x01 \x01(\v2\x15.data.v1.SafeDataMetaH\x00R\x04meta\x12.\n" +
	"\x05chunk\x18\x02 \x01(\v2\x16.data.v1.SafeDataChunkH\x00R\x05chunkB\x0e\n" +
	"\frequest_type\"L\n" +
	"\x17GetSafeDataListResponse\x121\n" +
	"\bsobjects\x18\x01 \x03(\v2\x15.data.v1.SafeDataMetaR\bsobjects2\x89\x03\n" +
	"\x0fSafeDataService\x12J\n" +
	"\vNewSafeData\x12\x1b.data.v1.NewSafeDataRequest\x1a\x1c.data.v1.NewSafeDataResponse(\x01\x12B\n" +
	"\vDelSafeData\x12\x1b.data.v1.DelSafeDataRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\fEditSafeData\x12\x1c.data.v1.EditSafeDataRequest\x1a\x1d.data.v1.EditSafeDataResponse(\x01\x12J\n" +
	"\vGetSafeData\x12\x1b.data.v1.GetSafeDataRequest\x1a\x1c.data.v1.GetSafeDataResponse0\x01\x12K\n" +
	"\x0fGetSafeDataList\x12\x16.google.protobuf.Empty\x1a .data.v1.GetSafeDataListResponseB\bZ\x06./datab\beditionsp\xe8\a"

var file_data_data_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_data_data_proto_goTypes = []any{
	(*SafeDataMeta)(nil),            // 0: data.v1.SafeDataMeta
	(*SafeDataChunk)(nil),           // 1: data.v1.SafeDataChunk
	(*NewSafeDataRequest)(nil),      // 2: data.v1.NewSafeDataRequest
	(*NewSafeDataResponse)(nil),     // 3: data.v1.NewSafeDataResponse
	(*DelSafeDataRequest)(nil),      // 4: data.v1.DelSafeDataRequest
	(*EditSafeDataRequest)(nil),     // 5: data.v1.EditSafeDataRequest
	(*EditSafeDataResponse)(nil),    // 6: data.v1.EditSafeDataResponse
	(*GetSafeDataRequest)(nil),      // 7: data.v1.GetSafeDataRequest
	(*GetSafeDataResponse)(nil),     // 8: data.v1.GetSafeDataResponse
	(*GetSafeDataListResponse)(nil), // 9: data.v1.GetSafeDataListResponse
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 11: google.protobuf.Empty
}
var file_data_data_proto_depIdxs = []int32{
	10, // 0: data.v1.SafeDataMeta.updated:type_name -> google.protobuf.Timestamp
	0,  // 1: data.v1.NewSafeDataRequest.meta:type_name -> data.v1.SafeDataMeta
	1,  // 2: data.v1.NewSafeDataRequest.chunk:type_name -> data.v1.SafeDataChunk
	10, // 3: data.v1.NewSafeDataResponse.updated:type_name -> google.protobuf.Timestamp
	0,  // 4: data.v1.EditSafeDataRequest.meta:type_name -> data.v1.SafeDataMeta
	1,  // 5: data.v1.EditSafeDataRequest.chunk:type_name -> data.v1.SafeDataChunk
	10, // 6: data.v1.EditSafeDataResponse.updated:type_name -> google.protobuf.Timestamp
	0,  // 7: data.v1.GetSafeDataResponse.meta:type_name -> data.v1.SafeDataMeta
	1,  // 8: data.v1.GetSafeDataResponse.chunk:type_name -> data.v1.SafeDataChunk
	0,  // 9: data.v1.GetSafeDataListResponse.sobjects:type_name -> data.v1.SafeDataMeta
	2,  // 10: data.v1.SafeDataService.NewSafeData:input_type -> data.v1.NewSafeDataRequest
	4,  // 11: data.v1.SafeDataService.DelSafeData:input_type -> data.v1.DelSafeDataRequest
	5,  // 12: data.v1.SafeDataService.EditSafeData:input_type -> data.v1.EditSafeDataRequest
	7,  // 13: data.v1.SafeDataService.GetSafeData:input_type -> data.v1.GetSafeDataRequest
	11, // 14: data.v1.SafeDataService.GetSafeDataList:input_type -> google.protobuf.Empty
	3,  // 15: data.v1.SafeDataService.NewSafeData:output_type -> data.v1.NewSafeDataResponse
	11, // 16: data.v1.SafeDataService.DelSafeData:output_type -> google.protobuf.Empty
	6,  // 17: data.v1.SafeDataService.EditSafeData:output_type -> data.v1.EditSafeDataResponse
	8,  // 18: data.v1.SafeDataService.GetSafeData:output_type -> data.v1.GetSafeDataResponse
	9,  // 19: data.v1.SafeDataService.GetSafeDataList:output_type -> data.v1.GetSafeDataListResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_data_data_proto_init() }
func file_data_data_proto_init() {
	if File_data_data_proto != nil {
		return
	}
	file_data_data_proto_msgTypes[2].OneofWrappers = []any{
		(*newSafeDataRequest_Meta)(nil),
		(*newSafeDataRequest_Chunk)(nil),
	}
	file_data_data_proto_msgTypes[5].OneofWrappers = []any{
		(*editSafeDataRequest_Meta)(nil),
		(*editSafeDataRequest_Chunk)(nil),
	}
	file_data_data_proto_msgTypes[8].OneofWrappers = []any{
		(*getSafeDataResponse_Meta)(nil),
		(*getSafeDataResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_data_proto_rawDesc), len(file_data_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_data_proto_goTypes,
		DependencyIndexes: file_data_data_proto_depIdxs,
		MessageInfos:      file_data_data_proto_msgTypes,
	}.Build()
	File_data_data_proto = out.File
	file_data_data_proto_goTypes = nil
	file_data_data_proto_depIdxs = nil
}
