// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: data/data.proto

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SafeDataService_NewSafeData_FullMethodName     = "/data.v1.SafeDataService/NewSafeData"
	SafeDataService_DelSafeData_FullMethodName     = "/data.v1.SafeDataService/DelSafeData"
	SafeDataService_EditSafeData_FullMethodName    = "/data.v1.SafeDataService/EditSafeData"
	SafeDataService_GetSafeData_FullMethodName     = "/data.v1.SafeDataService/GetSafeData"
	SafeDataService_GetSafeDataList_FullMethodName = "/data.v1.SafeDataService/GetSafeDataList"
)

// SafeDataServiceClient is the client API for SafeDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SafeDataService - Сервис хранения зашифрованных объектов
type SafeDataServiceClient interface {
	// NewSafeData - новый зашифрованный объект
	NewSafeData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NewSafeDataRequest, NewSafeDataResponse], error)
	// DelSafeData - Удаление на сервере
	DelSafeData(ctx context.Context, in *DelSafeDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// EditSafeData - Изменение на сервере
	EditSafeData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EditSafeDataRequest, EditSafeDataResponse], error)
	// GetSafeData - получение конкретного зашифрованного объекта
	GetSafeData(ctx context.Context, in *GetSafeDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSafeDataResponse], error)
	// GetSafeDataList - получение списка объектов
	GetSafeDataList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSafeDataListResponse, error)
}

type safeDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSafeDataServiceClient(cc grpc.ClientConnInterface) SafeDataServiceClient {
	return &safeDataServiceClient{cc}
}

func (c *safeDataServiceClient) NewSafeData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NewSafeDataRequest, NewSafeDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SafeDataService_ServiceDesc.Streams[0], SafeDataService_NewSafeData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NewSafeDataRequest, NewSafeDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SafeDataService_NewSafeDataClient = grpc.ClientStreamingClient[NewSafeDataRequest, NewSafeDataResponse]

func (c *safeDataServiceClient) DelSafeData(ctx context.Context, in *DelSafeDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SafeDataService_DelSafeData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safeDataServiceClient) EditSafeData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EditSafeDataRequest, EditSafeDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SafeDataService_ServiceDesc.Streams[1], SafeDataService_EditSafeData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EditSafeDataRequest, EditSafeDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SafeDataService_EditSafeDataClient = grpc.ClientStreamingClient[EditSafeDataRequest, EditSafeDataResponse]

func (c *safeDataServiceClient) GetSafeData(ctx context.Context, in *GetSafeDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSafeDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SafeDataService_ServiceDesc.Streams[2], SafeDataService_GetSafeData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSafeDataRequest, GetSafeDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SafeDataService_GetSafeDataClient = grpc.ServerStreamingClient[GetSafeDataResponse]

func (c *safeDataServiceClient) GetSafeDataList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSafeDataListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSafeDataListResponse)
	err := c.cc.Invoke(ctx, SafeDataService_GetSafeDataList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SafeDataServiceServer is the server API for SafeDataService service.
// All implementations must embed UnimplementedSafeDataServiceServer
// for forward compatibility.
//
// SafeDataService - Сервис хранения зашифрованных объектов
type SafeDataServiceServer interface {
	// NewSafeData - новый зашифрованный объект
	NewSafeData(grpc.ClientStreamingServer[NewSafeDataRequest, NewSafeDataResponse]) error
	// DelSafeData - Удаление на сервере
	DelSafeData(context.Context, *DelSafeDataRequest) (*emptypb.Empty, error)
	// EditSafeData - Изменение на сервере
	EditSafeData(grpc.ClientStreamingServer[EditSafeDataRequest, EditSafeDataResponse]) error
	// GetSafeData - получение конкретного зашифрованного объекта
	GetSafeData(*GetSafeDataRequest, grpc.ServerStreamingServer[GetSafeDataResponse]) error
	// GetSafeDataList - получение списка объектов
	GetSafeDataList(context.Context, *emptypb.Empty) (*GetSafeDataListResponse, error)
	mustEmbedUnimplementedSafeDataServiceServer()
}

// UnimplementedSafeDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSafeDataServiceServer struct{}

func (UnimplementedSafeDataServiceServer) NewSafeData(grpc.ClientStreamingServer[NewSafeDataRequest, NewSafeDataResponse]) error {
	return status.Error(codes.Unimplemented, "method NewSafeData not implemented")
}
func (UnimplementedSafeDataServiceServer) DelSafeData(context.Context, *DelSafeDataRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelSafeData not implemented")
}
func (UnimplementedSafeDataServiceServer) EditSafeData(grpc.ClientStreamingServer[EditSafeDataRequest, EditSafeDataResponse]) error {
	return status.Error(codes.Unimplemented, "method EditSafeData not implemented")
}
func (UnimplementedSafeDataServiceServer) GetSafeData(*GetSafeDataRequest, grpc.ServerStreamingServer[GetSafeDataResponse]) error {
	return status.Error(codes.Unimplemented, "method GetSafeData not implemented")
}
func (UnimplementedSafeDataServiceServer) GetSafeDataList(context.Context, *emptypb.Empty) (*GetSafeDataListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSafeDataList not implemented")
}
func (UnimplementedSafeDataServiceServer) mustEmbedUnimplementedSafeDataServiceServer() {}
func (UnimplementedSafeDataServiceServer) testEmbeddedByValue()                         {}

// UnsafeSafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SafeDataServiceServer will
// result in compilation errors.
type UnsafeSafeDataServiceServer interface {
	mustEmbedUnimplementedSafeDataServiceServer()
}

func RegisterSafeDataServiceServer(s grpc.ServiceRegistrar, srv SafeDataServiceServer) {
	// If the following call panics, it indicates UnimplementedSafeDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SafeDataService_ServiceDesc, srv)
}

func _SafeDataService_NewSafeData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SafeDataServiceServer).NewSafeData(&grpc.GenericServerStream[NewSafeDataRequest, NewSafeDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SafeDataService_NewSafeDataServer = grpc.ClientStreamingServer[NewSafeDataRequest, NewSafeDataResponse]

func _SafeDataService_DelSafeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelSafeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafeDataServiceServer).DelSafeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SafeDataService_DelSafeData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafeDataServiceServer).DelSafeData(ctx, req.(*DelSafeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SafeDataService_EditSafeData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SafeDataServiceServer).EditSafeData(&grpc.GenericServerStream[EditSafeDataRequest, EditSafeDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SafeDataService_EditSafeDataServer = grpc.ClientStreamingServer[EditSafeDataRequest, EditSafeDataResponse]

func _SafeDataService_GetSafeData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSafeDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SafeDataServiceServer).GetSafeData(m, &grpc.GenericServerStream[GetSafeDataRequest, GetSafeDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SafeDataService_GetSafeDataServer = grpc.ServerStreamingServer[GetSafeDataResponse]

func _SafeDataService_GetSafeDataList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafeDataServiceServer).GetSafeDataList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SafeDataService_GetSafeDataList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafeDataServiceServer).GetSafeDataList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SafeDataService_ServiceDesc is the grpc.ServiceDesc for SafeDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SafeDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.v1.SafeDataService",
	HandlerType: (*SafeDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DelSafeData",
			Handler:    _SafeDataService_DelSafeData_Handler,
		},
		{
			MethodName: "GetSafeDataList",
			Handler:    _SafeDataService_GetSafeDataList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NewSafeData",
			Handler:       _SafeDataService_NewSafeData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "EditSafeData",
			Handler:       _SafeDataService_EditSafeData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetSafeData",
			Handler:       _SafeDataService_GetSafeData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data/data.proto",
}
